#!/bin/bash
# Install a desktop entry + launcher so Tabs shows up in GNOME Activities and
# can be bound to a keyboard shortcut via Settings → Keyboard → Custom Shortcuts.
#
# Re-run this after moving the project directory. Re-run after `npm run build`
# is NOT required — the launcher executes the built files in-place.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications"
APP_ID="tabs-browser"

mkdir -p "$BIN_DIR" "$APPS_DIR"

LAUNCHER="$BIN_DIR/$APP_ID"
DESKTOP="$APPS_DIR/$APP_ID.desktop"

cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-app.sh. Re-run it to regenerate.
# Invoke the compiled Electron binary directly — the node_modules/.bin/electron
# shim is a Node script, and a GNOME-launched environment has no \`node\` on PATH.
unset ELECTRON_RUN_AS_NODE
exec "$PROJECT_DIR/node_modules/electron/dist/electron" \\
    "$PROJECT_DIR/out/main/index.js" \\
    "\$@"
EOF
chmod +x "$LAUNCHER"

cat > "$DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=Tabs
Comment=Custom browser with configurable site tabs
Exec=$LAUNCHER %U
Icon=web-browser
Categories=Network;WebBrowser;
StartupNotify=true
StartupWMClass=$APP_ID
Terminal=false
EOF

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$APPS_DIR" >/dev/null
fi

cat <<EOF

Installed:
  Launcher      $LAUNCHER
  Desktop entry $DESKTOP

The app should now appear in GNOME Activities as "Tabs".

To bind a keyboard shortcut:
  Settings → Keyboard → View and Customize Shortcuts → Custom Shortcuts → +
    Name:     Focus Tabs
    Command:  gtk-launch $APP_ID
    Shortcut: (press your preferred keys)

Before first use, make sure you have built the app:
  npm run build
EOF
